name: Duplicate Mappings
on:
  push:
  pull_request:
jobs:
  update-mappings:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Duplicate Mappings
        shell: bash
        run: |
          make duplicate.mapping OS_ARCH=darwin_amd64
          make duplicate.mapping OS_ARCH=darwin_arm64
          make duplicate.mapping OS_ARCH=linux_amd64
          make duplicate.mapping OS_ARCH=linux_arm64
          make duplicate.mapping OS_ARCH=windows_amd64
      - name: Push Duplicated Mappings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push duplicated mappings