name: Duplicate Mappings
on:
  push:
  pull_request:
jobs:
  update-mappings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Duplicate Mappings
        shell: bash
        run: |
          cp mapping.go mapping.go
          sed -i '6s_.*_	bindings "github.com/duckdb/duckdb-go-bindings"_g' mapping.go
      - name: Push Duplicated Mappings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push duplicated mappings