name: Duplicate Arrow Mappings
on:
  workflow_dispatch:
jobs:
  update-arrow-mappings:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Duplicate Arrow Mappings
        shell: bash
        run: |
          make duplicate.arrow.mapping OS_ARCH=darwin_amd64
          make duplicate.arrow.mapping OS_ARCH=darwin_arm64
          make duplicate.arrow.mapping OS_ARCH=linux_amd64
          make duplicate.arrow.mapping OS_ARCH=linux_arm64
          make duplicate.arrow.mapping OS_ARCH=windows_amd64
      - name: Push Duplicated Arrow Mappings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push duplicated arrow mappings