name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  go_test:
    name: Main Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        go: ["1.23"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Main Tests
        run: |
          go test -v -race -count=1 .

  test_examples:
    name: Test Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [ "1.23" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test Examples
        run: make examples

  test-arrow:
    name: Test Arrow
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ "1.23" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Arrow Tests
        run: go test -v -race -count=1 -tags=duckdb_arrow

  test-dynamic-lib:
    name: Dynamic Lib Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: "macos-13"
            filename: "libduckdb-osx-universal"
            filepath: "DYLD_LIBRARY_PATH"
          - os: "macos-14"
            filename: "libduckdb-osx-universal"
            filepath: "DYLD_LIBRARY_PATH"
          - os: "ubuntu-latest"
            filename: "libduckdb-linux-amd64"
            filepath: "LD_LIBRARY_PATH"
          - os: "ubuntu-24.04-arm"
            filename: "libduckdb-linux-aarch64"
            filepath: "LD_LIBRARY_PATH"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run Dynamic Lib Tests
        run: |
          make test.dynamic.lib FILENAME=${{ matrix.filename }}
          CGO_ENABLED=1 CGO_LDFLAGS="-lduckdb -L${SRCDIR}dynamic-dir/" ${{ matrix.filepath }}=${SRCDIR}dynamic-dir/ go test
